// DATA  ---------------------------------------------------------
export let QUIZ_DATA = [
  {
    title: "What does HTML stand for?",
    choiceA: "Hi Thierry More Laught",
    choiceB: "How To move Left",
    choiceC: "Ho Theary Missed the Laundry !",
    choiceD: "Hypertext Markup Language",
    correct: "D",
  },
  {
    title: "What does CSS stand for?",
    choiceA: "Cisco and Super Start",
    choiceB: "Ci So Sa",
    choiceC: "Cascading Style Sheets ",
    choiceD: "I don't know !",
    correct: "C",
  },
  {
    title: "What does JS stand for?",
    choiceA: "Junior stars",
    choiceB: "Justing Star",
    choiceC: "Javascript",
    choiceD: "RonanScript",
    correct: "C",
  },
  {
    title: "Which tag is used to create a link in HTML?",
    choiceA: "<p>",
    choiceB: "<a>",
    choiceC: "<div>",
    choiceD: "<img>",
    correct: "B",
  },
  {
    title: "Which property is used to change text color in CSS?",
    choiceA: "background-color",
    choiceB: "font-style",
    choiceC: "color",
    choiceD: "text-align",
    correct: "C",
  }, 
  {
    title: "Which HTML tag is used to insert an image?",
    choiceA: "<image>",
    choiceB: "<img>",
    choiceC: "<picture>",
    choiceD: "<src>",
    correct: "B",
  }, 
  {
    title: "Which CSS property is used to change background color?",
    choiceA: "color",
    choiceB: "background-color",
    choiceC: "font-color",
    choiceD: "bgcolor",
    correct: "B",
  },
  {
    title: "Which symbol is used for single-line comments in JavaScript?",
    choiceA: "//",
    choiceB: "/* */",
    choiceC: "#",
    choiceD: "<!-- -->",
    correct: "A",
  },
  {
    title: "Which keyword is used to declare a variable in JavaScript?",
    choiceA: "int",
    choiceB: "let",
    choiceC: "string",
    choiceD: "define",
    correct: "B",
  },
  {
    title: "Which HTML tag is used to create a paragraph?",
    choiceA: "<para>",
    choiceB: "<text>",
    choiceC: "<p>",
    choiceD: "<h1>",
    correct: "C",
  }
];